import React,{useState,useEffect} from 'react';
import {Icon,Button,Badge,Heading,Empty,ErrorNotice,pretty,when,api,post} from './ui';
import {isRubricV2} from './scoring';

export function Knowledge(){
  const [products,setProducts]=useState([]);const [selected,setSelected]=useState(null);const [query,setQuery]=useState('');const [results,setResults]=useState(null);const [error,setError]=useState('');const [busy,setBusy]=useState(false);
  useEffect(()=>{api('/products').then(d=>{setProducts(d.products);setSelected(d.products[0])}).catch(e=>setError(e.message))},[]);
  async function retrieve(e){e.preventDefault();setBusy(true);setError('');try{const d=await api(`/products/${selected.id}/retrieve?q=${encodeURIComponent(query)}`);setResults(d)}catch(e){setError(e.message)}finally{setBusy(false)}}
  return <>
    <Heading eyebrow="THE TECHNOLOGY BEHIND THE MATCH" title="Start with what the product can do.">The supplied technical sheets are the source of truth for applications and constraints.</Heading>
    <ErrorNotice error={error}/>
    <div className="product-selector">{products.map(p=><button className={selected?.id===p.id?'selected':''} key={p.id} onClick={()=>{setSelected(p);setResults(null);setQuery('')}}><span className={`product-mini-art ${p.id.includes('NT')?'mint':'lilac'}`}><Icon name={p.id.includes('NT')?'layers':'bolt'} size={27}/></span><div><span>{p.family}</span><h2>{p.name}</h2><small>Supplied case-study software</small></div><Icon name={selected?.id===p.id?'check':'arrow'} size={20}/></button>)}</div>
    {selected?<div className="knowledge-layout"><section className="panel product-detail"><div className="panel-heading split"><h2>Product profile</h2><Badge>Fictional product</Badge></div><p>{selected.description}</p><h3 className="small-title">WHERE IT FITS</h3><div className="application-tags">{selected.applications.map(a=><span key={a}>{a}</span>)}</div><h3 className="small-title">TECHNICAL BOUNDARIES</h3><div className="spec-list">{selected.specs.map((s,i)=><div key={i}><span>{s.label}</span><strong>{s.value}</strong><small>p. {s.page}</small></div>)}</div><a className="button secondary full" href={selected.document_url} target="_blank" rel="noreferrer"><Icon name="file" size={17}/>Open product spec sheet<Icon name="external" size={15}/></a><div className="quiet-note"><Icon name="info" size={14}/><span>Product properties are not customer requirements. Suitability still needs application validation.</span></div></section>
    <section className="panel retrieval-panel"><div className="panel-heading"><span className="icon-tile"><Icon name="search"/></span><div><h2>Find the supporting passage</h2><p>Query the actual PDF text, with page-level provenance.</p></div></div><form className="retrieval-form" onSubmit={retrieve}><label className="search-input"><Icon name="search" size={17}/><input aria-label="Search product knowledge" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Try ‘latency’ or ‘predictive maintenance’" required/></label><Button kind="primary" type="submit" disabled={busy||!query.trim()}>{busy?'Searching...':'Retrieve'}</Button></form><div className="retrieval-method"><Badge tone="purple">Product-filtered lexical retrieval</Badge><span>Source text, no generated answer</span></div><div className="chunk-list">{(results?.chunks??selected.chunks.slice(0,3)).map((c,i)=><article className="chunk-card" key={c.id}><div><span className="chunk-icon"><Icon name="file" size={15}/></span><strong>{c.title||`Passage ${i+1}`}</strong><Badge>Page {c.page}</Badge></div><p>{c.text}</p><footer><span>{c.source}</span>{c.score!==undefined&&<span>Retrieval score {Number(c.score).toFixed(2)}</span>}</footer></article>)}{results&&!results.chunks.length&&<Empty icon="search" title="No matching passages">Try a technical term from the sheet, such as latency, throughput, MQTT, Kafka or deployment.</Empty>}</div></section></div>:!error&&<div className="loading-state"><span className="spinner"/>Reading the product library...</div>}
  </>
}

const nodes=[
  {id:'scope',icon:'target',label:'Confirm scope',type:'HUMAN CHECKPOINT',desc:'Turn a bounded research request into an explicit product, geography and application. Pause until the user confirms.',contract:'Input: natural-language brief + selected scenario\nOutput: approved scope\nState: SQLite LangGraph checkpoint\nResume: Command(resume=...)',boundary:'Captured mode recognizes three prepared scopes. Live mode supports open requests for either supplied software product, with a human confirming the interpretation.'},
  {id:'retrieve',icon:'book',label:'Retrieve product context',type:'RETRIEVAL',desc:'Retrieve relevant text from the supplied product PDF. Keep the product identifier, original page and text with every chunk.',contract:'Input: product + application\nTool: product-filtered lexical retrieval\nOutput: source text + page references\nBoundary: fictional product spec sheets',boundary:'No vector search is claimed. With two small PDFs, lexical retrieval is inspectable and sufficient for the demonstration.'},
  {id:'discover',icon:'search',label:'Connect public evidence',type:'CAPTURED RESEARCH',desc:'Replay public research excerpts and assemble company evidence. Separate directly supported claims from suitability inferences and missing information.',contract:'Input: approved scenario + source captures\nOutput: typed lead evidence\nProvenance: source-backed | inferred | unknown\nNetwork / model calls in this run: 0',boundary:'Discovery and model extraction are captured inputs. Freshness is the original capture date, never the date of replay.'},
  {id:'rank',icon:'filter',label:'Gate & rank',type:'DETERMINISTIC CODE',desc:'Check hard technical incompatibilities before considering commercial priority. Apply the same four-criterion policy to every lead.',contract:'Application fit: 40 points\nCompany size: 20 points\nSector: 20 points\nSupply-chain position: 20 points\nEvidence coverage: reported separately',boundary:'Captured policy v1 retains zero points for unknown size and its original evidence rules. This is historical behavior. New live research uses rubric v2 with explicit unknowns and score ranges.'},
  {id:'review',icon:'people',label:'Assess & decide',type:'HUMAN CHECKPOINT',desc:'A qualification graph waits for an explicit human decision. Require a rationale, reject blocked approvals and persist the outcome.',contract:'Input: lead + evidence + decision + note\nDecisions: approve | reject | needs_research\nApproval: persist opportunity in local pipeline\nReplay: idempotent pipeline identity',boundary:'Local reviewer attribution is for demonstration. Production needs authenticated identities, authorization and stronger audit controls.'},
  {id:'track',icon:'pipeline',label:'Track the opportunity',type:'PERSISTED STATE',desc:'Keep follow-up stages, customer notes, source age checks and activity history together. Export a reviewable local JSON record.',contract:'Storage: SQLite\nLifecycle: qualified → contacted → discovery → closed\nUpdates: stage + required context\nFreshness: age of saved evidence',boundary:'CRM sync, scheduled web refresh and automatic response interpretation are planned integrations, not active capabilities.'},
];
const liveNodes=[
  {id:'scope',icon:'target',label:'Confirm scope',type:'HUMAN CHECKPOINT',desc:'Gemini interprets the brief for the selected product. A human confirms product, geography, application and additional constraints before public search.',contract:'Model call 1: interpret brief, before graph execution\nGraph: confirm_scope interrupt\nOutput: approved research scope\nResume: Command(resume=...)',boundary:'The interpreted scope is a proposal until the user confirms it. Failed live research stays visible; captured replay is a separate explicit choice.'},
  {id:'retrieve',icon:'book',label:'Retrieve product context',type:'RETRIEVAL',desc:'Retrieve passages from the supplied product PDF, retaining product identity and original page references for assessment.',contract:'Graph: retrieve_product\nTool: product-filtered BM25 retrieval\nOutput: product passages + page citations\nProducts: two fictional case-study software specifications',boundary:'The demo uses lexical retrieval. Product properties describe the supplied software; they do not establish a customer requirement.'},
  {id:'discover',icon:'search',label:'Research public sources',type:'GROUNDED SEARCH',desc:'Gemini uses Google Search within the approved scope. The server fetches a bounded selection of cited public pages and retains the search provenance.',contract:'Graph: discover_candidates\nModel call 2: Gemini + Google Search\nOutput: findings + source IDs + available page text\nContext: approved scope and product context',boundary:'Search summaries can suggest leads. They are distinct from fetched source text, and neither automatically proves commercial demand.'},
  {id:'extract',icon:'file',label:'Extract and validate evidence',type:'STRUCTURED EVIDENCE',desc:'Extract candidate facts with original quotations, source identifiers, entity scope and available dates. Validate the structure, source references and available quotations.',contract:'Graph: extract_evidence\nModel call 3: typed candidate evidence\nContext: public findings + product passages\nOutput: facts, provenance and validation issues',boundary:'A matching quotation proves that wording appeared in the retrieved text. Semantic support, entity attribution, negation and commercial interpretation still need assessment.'},
  {id:'assess',icon:'target',label:'Assess fit against the rubric',type:'LLM ASSESSMENT',desc:'A separate LLM call reviews evidence support and makes nuanced criterion-level judgments against product-specific anchors. Each accepted rating has a rationale, supporting fact IDs and visible gaps.',contract:'Graph: assess_fit\nModel call 4: structured rubric assessment\nRatings: 0-5, or unknown\nCriteria: workload scale, application, sector, role\nCommercial judgment remains an inference',boundary:'Unknown is distinct from an evidenced poor fit. Summary-only judgments can remain provisional evidence; a model response is not independent verification of the source.'},
  {id:'rank',icon:'filter',label:'Calculate scores and apply gates',type:'DETERMINISTIC CODE',desc:'Code validates assessment references and applies the versioned weights. It reports possible points for unknown criteria, checks technical constraints and orders the shortlist.',contract:'Graph: calculate_scores, technical_gate, rank_candidates\nWeights: scale 20, application 40, sector 20, role 20\nKnown points: sum(rating / 5 × criterion weight)\nUpper bound: known points + unknown weights\nEvidence coverage and completeness: separate metrics',boundary:'All maxima are reachable under the rubric. The range represents unresolved points, not a probability interval. Demo weights still need Sales calibration. Hard technical conflicts block approval regardless of fit.'},
  {id:'review',icon:'people',label:'Human review and decision',type:'HUMAN CHECKPOINT',desc:'A separate qualification graph waits for a human decision and required rationale. The backend rejects blocked approvals and saves the result with the assessed lead.',contract:'Graph: human_decision interrupt → persist_decision\nDecisions: approve | reject | needs_research\nApproval: create local pipeline opportunity\nHistory: original assessment and policy retained',boundary:'Needs research records the decision for this run; it does not launch another search. New runs do not automatically inherit a company review. Production requires authenticated reviewers and shared company identity.'},
  {id:'track',icon:'pipeline',label:'Track the opportunity',type:'PERSISTED STATE',desc:'Retain the approved opportunity, evidence and human rationale. Record follow-up stages, customer notes and the age of saved sources.',contract:'Storage: local SQLite\nLifecycle: qualified → contacted → discovery → closed\nUpdates: stage + required context\nExport: local JSON download',boundary:'CRM delivery and scheduled evidence refresh are proposed integrations. The live demo is a controlled workflow with four normal LLM calls, not autonomous multi-agent orchestration.'},
];

export function Engineering({data,navigate}){
  const [active,setActive]=useState(0);const [selectedRun,setSelectedRun]=useState(data.runs[0]?.id||'');const [run,setRun]=useState(null);const [evals,setEvals]=useState(null);const [busy,setBusy]=useState(false);const [error,setError]=useState('');
  useEffect(()=>{api('/evals').then(setEvals).catch(e=>setError(e.message))},[]);
  useEffect(()=>{if(selectedRun)api(`/runs/${selectedRun}`).then(setRun).catch(e=>setError(e.message))},[selectedRun]);
  async function evaluate(){setBusy(true);setError('');try{setEvals(await post('/evals',{}))}catch(e){setError(e.message)}finally{setBusy(false)}}
  const liveView=(run?.mode || data.default_mode)==='live';
  const displayNodes=liveView?liveNodes:nodes;
  const historicalTrace=run?.leads?.some(lead=>!isRubricV2(lead));
  const activeIndex=Math.min(active,displayNodes.length-1);
  const node=displayNodes[activeIndex];
  return <>
    <Heading eyebrow="BUILT TO BE EXPLAINED" title="The decisions behind the system." action={<Badge tone={liveView?'purple':'green'} dot>{liveView?'Live research + local controls':'Captured research + local controls'}</Badge>}>A bounded workflow, traceable evidence, and a person at the decision boundary.</Heading><ErrorNotice error={error}/>
    <div className="engineering-principles">{[['graph','LangGraph','Stateful orchestration'],['book','RAG context','Product passages + sources'],['people','Human review','Checkpoint, decide, resume'],['shield','Controlled assessment','Rubric judgments + code gates']].map(([icon,title,desc])=><div key={title}><span className="icon-tile small"><Icon name={icon} size={20}/></span><div><strong>{title}</strong><small>{desc}</small></div></div>)}</div>
    <section className="panel workflow-panel"><div className="panel-heading split"><div><h2>From a brief to an opportunity</h2><p>{liveView?'Current live workflow: select a step to inspect its contract.':'Captured replay retains its historical policy: inspect each step.'}</p></div><span className="subtle">Three graph definitions · Persistent checkpoints</span></div><div className="workflow-layout"><div className="workflow-map">{displayNodes.map((n,i)=><React.Fragment key={n.id}><button className={`workflow-node ${i===activeIndex?'selected':''} ${n.type==='HUMAN CHECKPOINT'?'human':''}`} onClick={()=>setActive(i)}><span className="node-icon"><Icon name={n.icon} size={20}/></span><div><small>{String(i+1).padStart(2,'0')} / {n.type}</small><strong>{n.label}</strong></div>{n.type==='HUMAN CHECKPOINT'?<span className="pause-symbol">Ⅱ</span>:<Icon name="arrow" size={16}/>}</button>{i<displayNodes.length-1&&<div className="node-connector"><i/></div>}</React.Fragment>)}<div className="map-caption"><i className="checkpoint-dot"/>Purple outline = human decision boundary</div></div><article className="node-detail" key={node.id}><Badge tone="purple">{node.type}</Badge><h2>{node.label}</h2><p>{node.desc}</p><h3>Execution contract</h3><pre>{node.contract}</pre><div className="node-boundary"><Icon name="info" size={18}/><p>{node.boundary}</p></div>{activeIndex===1&&<Button kind="secondary" onClick={()=>navigate('/knowledge')}>Inspect product retrieval<Icon name="arrow" size={16}/></Button>}<div className="node-docs"><a href="https://docs.langchain.com/oss/python/langgraph/interrupts" target="_blank" rel="noreferrer">LangGraph interrupt semantics<Icon name="external" size={13}/></a><span>Research resumes after scope confirmation. Qualification uses a separate decision graph.</span></div></article></div></section>
    <div className="engineering-detail-grid"><section className="panel execution-panel"><div className="panel-heading split"><div><h2>Execution, with a trail</h2><p>Recorded events from your research run.</p></div><Icon name="graph" size={20}/></div>{data.runs.length?<><select className="full" aria-label="Research run trace" value={selectedRun} onChange={e=>setSelectedRun(e.target.value)}>{data.runs.map(r=><option key={r.id} value={r.id}>{r.title} · {r.id.slice(0,6)}</option>)}</select>{run&&<>{historicalTrace&&<div className="policy-notice"><Icon name="info" size={15}/><p>This trace belongs to a {run.mode==='replay'?'captured':'historical'} policy v1 assessment. Its recorded calls and scores are preserved.</p></div>}<div className="trace-meta"><Badge tone="green">{pretty(run.status)}</Badge><span>{run.trace.length} events · {run.usage?.model_calls||0} live model calls</span></div>{run.mode==='live'&&<div className="usage-summary"><span>{run.usage?.search_calls||0} grounded search calls</span><span>{(run.usage?.total_tokens||0).toLocaleString()} tokens reported</span><span>{(run.usage?.models||[]).join(', ')}</span>{run.usage_complete===false&&<span>Failed-attempt usage may be incomplete</span>}</div>}<div className="trace-list">{run.trace.map((t,i)=><div key={i}><span className={`trace-dot ${['waiting','interrupted'].includes(t.status)?'amber':'green'}`}><Icon name={['waiting','interrupted'].includes(t.status)?'people':'check'} size={12}/></span><div><strong>{t.label||pretty(t.node)}</strong><p>{t.detail}</p><small>{when(t.at)}</small></div>{t.duration_ms!==undefined&&<span className="trace-time">{t.duration_ms>1000?`${(t.duration_ms/1000).toFixed(1)} s`:`${Number(t.duration_ms).toFixed(0)} ms`}</span>}</div>)}</div></>}</>:<Empty icon="graph" title="A real run leaves a real trace" action={<Button kind="secondary" onClick={()=>navigate('/')}>Create a research brief</Button>}>Run a research play to inspect the recorded execution and human decisions.</Empty>}</section>
    <section className="panel eval-panel"><div className="panel-heading split"><div><h2>Test the boundaries</h2><p>Executable regression checks, not a quality claim.</p></div><Icon name="shield" size={20}/></div><div className="eval-score"><strong>{evals?`${evals.passed}/${evals.total}`:'--'}</strong><div>{evals?'Checks passed':'Ready to evaluate'}<small>{evals?`Last run ${when(evals.at)}`:'No results until the checks run'}</small></div></div><Button kind="primary full" icon="play" onClick={evaluate} disabled={busy}>{busy?<><span className="spinner"/>Running checks</>:'Run evaluation checks'}</Button>{evals&&<div className="eval-checks">{evals.checks.map((c,i)=><div key={i}><span className={c.passed?'check-tile':'fail-tile'}><Icon name={c.passed?'check':'close'} size={13}/></span><div><strong>{c.name}</strong><p>{c.detail}</p></div></div>)}</div>}<div className="eval-boundary"><strong>What this does not measure</strong><p>Sales relevance, extraction accuracy and business impact need a separate labeled evaluation set and a real pilot. Passing regression checks does not establish production readiness.</p></div></section></div>
    <section className="production-section"><div className="section-heading"><div><h2>The path to production</h2><p>Ship in stages. Make the next investment answer a real uncertainty.</p></div><Badge>Proposed, not deployed</Badge></div><div className="production-grid">{[['01','Validate value','Partner with Sales','Label leads with sales specialists. Compare acceptance, time to a qualified shortlist and missed opportunities against manual research.'],['02','Harden the workflow','Add operational controls','Authenticated roles, durable workers, retry and cost budgets, hostile-page isolation, managed checkpoints and monitored model calls.'],['03','Close the loop','Integrate with the sales process','SAP C4C identity matching, idempotent delivery, owner routing, scheduled evidence refresh and feedback-driven policy review.']].map(([n,title,tag,desc])=><article key={n}><span>{n}</span><div><small>{tag}</small><h3>{title}</h3><p>{desc}</p></div></article>)}</div></section>
    <div className="policy-notice"><Icon name="graph" size={17}/><p><strong>Later pilot or production option:</strong> specialized research, assessment and verification agents could request targeted follow-up evidence. Introduce bounded loops only if measured quality gains justify their cost and latency. The demo keeps an explicit sequence and human review.</p></div>
    <div className="quiet-note"><Icon name="graph" size={15}/><span>Research and lead reviews share one worker and graph lock. The optional buyer check has its own worker and graph lock. <a href="/blueprint/langgraph-detail" onClick={e=>{e.preventDefault();navigate('/blueprint/langgraph-detail')}}>Inspect the exact graph nodes.</a></span></div>
    <div className="quiet-note"><Icon name="info" size={15}/><span>The current live workflow normally uses four model calls: scope, grounded search, evidence extraction and rubric assessment. Retries can add calls. Deterministic code calculates scores and enforces technical gates. Captured replay uses its original policy without model calls.</span></div>
  </>
}
