import React,{useState,useEffect} from 'react';
import {Icon,Button,Badge,Heading,Empty,CompanyMark,ErrorNotice,Modal,pretty,when,api,post} from './ui';
import {LeadStatus} from './Research';
import {FitValue,ScorePanel,evidenceAnchor} from './scoring';
import {EvidenceRecord} from './Evidence';

export function Assessment({runId,leadId,navigate,refresh,notify}){
  const [run,setRun]=useState(null);const [error,setError]=useState('');const [decision,setDecision]=useState(null);const [note,setNote]=useState('');const [busy,setBusy]=useState(false);const [activeEvidence,setActiveEvidence]=useState(null);
  useEffect(()=>{api(`/runs/${runId}`).then(setRun).catch(e=>setError(e.message))},[runId]);
  const lead=run?.leads.find(l=>l.id===leadId);
  async function review(e){e.preventDefault();setBusy(true);try{const updated=await post(`/runs/${runId}/leads/${leadId}/decision`,{decision,note});setRun(updated);setDecision(null);setNote('');refresh();notify(decision==='approve'?'Opportunity added to your pipeline.':decision==='reject'?'Decision recorded. Lead marked as not pursuing.':'Research request recorded.')}catch(e){setError(e.message)}finally{setBusy(false)}}
  if(!run)return <><ErrorNotice error={error}/><div className="loading-state">{!error&&<><span className="spinner"/>Opening lead assessment...</>}</div></>;
  if(!lead)return <Empty title="This lead could not be found" action={<Button onClick={()=>navigate(`/research/${runId}`)}>Back to research</Button>}>Return to the shortlist to choose an available lead.</Empty>;
  return <>
    <button className="back-link" onClick={()=>navigate(`/research/${runId}`)}><Icon name="back" size={15}/>Back to shortlist</button>
    <div className="assessment-heading"><CompanyMark name={lead.name} size="large"/><div><div className="eyebrow">LEAD ASSESSMENT</div><h1>{lead.name}</h1><div className="company-meta"><span>{lead.country}</span><i/><span>{pretty(lead.position)}</span><i/><span>{pretty(lead.sector)}</span></div></div><LeadStatus lead={lead}/></div>
    <ErrorNotice error={error}/>
    <div className="assessment-layout"><div className="assessment-main">
      <section className="panel opportunity-summary"><div className="eyebrow">THE OPPORTUNITY</div><h2>{lead.application}</h2><p>{lead.summary}</p><div className="material-match"><span className="icon-tile small"><Icon name="layers" size={18}/></span><div><span>Potential product match</span><strong>{run.scope.product_name}</strong></div><Badge tone="purple">Qualification hypothesis</Badge></div></section>
      <section className="panel evidence-panel"><div className="panel-heading split"><div><h2>The evidence behind the fit</h2><p>Read the claim. Check the source. Keep the uncertainty visible.</p></div><span className="source-count">{lead.evidence.length} records</span></div><div className="evidence-legend"><span><i className="legend-dot green"/>Source-backed</span><span><i className="legend-dot amber"/>Inferred</span><span><i className="legend-dot neutral"/>Unknown</span></div>{lead.evidence.map((e,i)=><EvidenceRecord key={e.id||e.fact_id} record={e} index={i} active={activeEvidence===(e.id||e.fact_id)}/>)}</section>
      {lead.validation_issues?.length>0&&<details className="panel validation-panel"><summary><Icon name="info" size={17}/><strong>Evidence checks and unresolved issues</strong><span>{lead.validation_issues.length}</span><Icon name="down" size={15}/></summary><p>These issues limit what this assessment can establish. Check the source and qualification questions before deciding.</p><ul>{lead.validation_issues.map((issue,i)=><li key={i}>{issue}</li>)}</ul></details>}
      <section className="panel gaps-panel"><div className="panel-heading"><span className="icon-tile amber"><Icon name="people"/></span><div><h2>The questions that move this forward</h2><p>Public research gets you to a conversation. These gaps need a person.</p></div></div>{lead.gaps.map((g,i)=><div className="gap-row" key={i}><span>{i+1}</span><p>{typeof g==='string'?g:g.question||g.detail}</p></div>)}{!lead.gaps.length&&<p className="muted">Review the supporting evidence before making a decision.</p>}<div className="next-action"><span>NEXT BEST ACTION</span><p>{lead.next_action}</p></div></section>
    </div><aside className="assessment-aside">
      <ScorePanel lead={lead} mode={run.mode} onEvidence={e=>{setActiveEvidence(e.id||e.fact_id);const element=document.getElementById(evidenceAnchor(e));element?.scrollIntoView({behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth',block:'center'});element?.focus({preventScroll:true})}}/>
      <section className={`technical-card ${lead.gate.status==='blocked'?'blocked':''}`}><Icon name="shield" size={22}/><div><strong>{lead.gate.status==='blocked'?'Technical mismatch':lead.gate.status==='review'?'Technical confirmation needed':'No known technical conflict'}</strong><p>{lead.gate.reason}</p></div></section>
      <section className="panel decision-panel"><div className="eyebrow">YOUR JUDGMENT MATTERS</div><h2>{lead.review?'A decision, with a record.':'Is this worth pursuing?'}</h2>{lead.review?<div className="decision-record"><Badge tone={lead.review.decision==='approve'?'green':'amber'}>{pretty(lead.review.decision)}</Badge><p>{lead.review.note}</p><small>{when(lead.review.at)}</small>{lead.review.decision==='approve'&&<Button kind="primary full" onClick={()=>navigate('/pipeline')}>Open pipeline<Icon name="arrow" size={16}/></Button>}</div>:<p>Approve a lead for follow-up, or capture why more work is needed.</p>}
      {!lead.review&&<><Button kind="primary full" icon="check" disabled={lead.gate.status==='blocked'} onClick={()=>{setDecision('approve');setError('')}}>Approve for pipeline</Button><div className="decision-secondary"><Button kind="secondary" onClick={()=>{setDecision('needs_research');setError('')}}>Needs research</Button><Button kind="ghost" onClick={()=>{setDecision('reject');setError('')}}>Not pursuing</Button></div></>}{lead.review&&lead.review.decision!=='approve'&&<Button kind="secondary full" onClick={()=>navigate('/')}>Start a new assessment<Icon name="arrow" size={15}/></Button>}<div className="decision-foot"><Icon name="shield" size={13}/>Decision + reason saved to the audit trail.</div></section>
    </aside></div>
    {decision&&<Modal title={decision==='approve'?'Move this opportunity forward':decision==='reject'?'Record your decision':'Request more research'} onClose={()=>!busy&&setDecision(null)}><form onSubmit={review}><div className="modal-company"><CompanyMark name={lead.name}/><div><strong>{lead.name}</strong><span>{run.scope.product_name}</span></div></div><p className="modal-intro">{decision==='approve'?'The lead will enter your local pipeline. This records commercial interest; technical validation and customer qualification still follow.':decision==='reject'?'Keep the reason visible so the same lead is not reassessed without context.':'Record the missing evidence or qualification question. This flags follow-up; it does not start live web research.'}</p><label className="form-label" htmlFor="review-note">Decision rationale <span>Required</span></label><textarea id="review-note" value={note} onChange={e=>setNote(e.target.value)} rows={4} required minLength={5} maxLength={1500} placeholder="Why is this the right next step? What still needs to be confirmed?" autoFocus/><ErrorNotice error={error}/><div className="modal-actions"><Button type="button" kind="ghost" onClick={()=>setDecision(null)} disabled={busy}>Cancel</Button><Button kind="primary" type="submit" disabled={busy||note.trim().length<5}>{busy?<><span className="spinner"/>Saving decision</>:decision==='approve'?'Approve & add to pipeline':'Save decision'}</Button></div></form></Modal>}
  </>
}

const columns=[['qualified','Qualified leads','A promising fit to follow up'],['contacted','Contacted','Start the right conversation'],['discovery','In discovery','Understand the real requirement'],['closed','Closed','Keep the outcome and learning']];
export function Pipeline({navigate,refresh,notify}){
  const [items,setItems]=useState(null);const [error,setError]=useState('');const [selected,setSelected]=useState(null);const [status,setStatus]=useState('');const [note,setNote]=useState('');const [busy,setBusy]=useState(false);const [search,setSearch]=useState('');
  useEffect(()=>{api('/pipeline').then(d=>setItems(d.items)).catch(e=>setError(e.message))},[]);
  function open(item){setSelected(item);setStatus(item.status);setNote('');setError('')}
  async function save(e){e.preventDefault();setBusy(true);try{const item=await api(`/pipeline/${selected.id}`,{method:'PATCH',body:JSON.stringify({status,note})});setItems(list=>list.map(x=>x.id===item.id?item:x));setSelected(item);setNote('');refresh();notify('Pipeline updated. Your note is in the activity history.')}catch(e){setError(e.message)}finally{setBusy(false)}}
  async function refreshEvidence(){setBusy(true);try{const item=await post(`/pipeline/${selected.id}/refresh`,{});setItems(list=>list.map(x=>x.id===item.id?item:x));setSelected(item);notify('Saved evidence checked. No new web research was performed.')}catch(e){setError(e.message)}finally{setBusy(false)}}
  function exportItems(){const payload={exported_at:new Date().toISOString(),destination:'local_download',note:'Demo export. Not sent to SAP C4C.',items};const u=URL.createObjectURL(new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=u;a.download='leadgen-pipeline.json';a.click();URL.revokeObjectURL(u);notify('Pipeline exported as JSON. No CRM records were created.')}
  return <>
    <Heading eyebrow="FROM INSIGHT TO ACTION" title="Keep the opportunity moving." action={<Button kind="secondary" icon="download" onClick={exportItems} disabled={!items?.length}>Export pipeline</Button>}>A shared record of what looks promising, what changed, and what comes next.</Heading>
    <ErrorNotice error={error}/>
    <div className="pipeline-toolbar"><label className="search-input"><Icon name="search" size={17}/><input aria-label="Search pipeline" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Find an opportunity..."/></label><span className="local-label"><i/>Local workspace · No CRM sync</span><Button kind="primary" icon="plus" onClick={()=>navigate('/')}>Discover opportunities</Button></div>
    {!items?<div className="loading-state">{!error&&<><span className="spinner"/>Loading pipeline...</>}</div>:!items.length?<section className="panel pipeline-empty"><Empty icon="pipeline" title="A good shortlist is only the beginning." action={<Button kind="primary" onClick={()=>navigate('/')}>Find your first opportunity<Icon name="arrow" size={16}/></Button>}>Assess a lead and approve it for follow-up. Your pipeline will keep the evidence, your decision, and every update together.</Empty><div className="empty-stages">{columns.map(([id,title],i)=><React.Fragment key={id}><span><b>{i+1}</b>{title}</span>{i<3&&<Icon name="arrow" size={16}/>}</React.Fragment>)}</div></section>:<div className="pipeline-board">{columns.map(([id,title,desc])=>{const filtered=items.filter(x=>x.status===id&&x.lead.name.toLowerCase().includes(search.toLowerCase()));return <section className={`pipeline-column stage-${id}`} key={id}><div className="column-heading"><span className="stage-dot"/><h2>{title}</h2><span className="column-count">{filtered.length}</span></div><p className="column-description">{desc}</p><div className="column-items">{filtered.map(item=><button className="pipeline-card" key={item.id} onClick={()=>open(item)}><div className="pipeline-card-top"><CompanyMark name={item.lead.name}/><span className="small-fit"><FitValue lead={item.lead} denominator={false}/><small>{item.lead.score_status==='provisional'?'provisional fit':'fit'}</small></span></div><h3>{item.lead.name}</h3><p>{item.lead.application}</p><span className="pipeline-product">{item.product_name}</span><div className="pipeline-card-bottom"><span><Icon name="file" size={13}/>{item.lead.evidence.length} evidence records</span><Icon name="arrow" size={15}/></div>{item.refresh?.status&&<small className="freshness-label">{pretty(item.refresh.status)}</small>}</button>)}{!filtered.length&&<div className="empty-column">No opportunities here yet</div>}</div></section>})}</div>}
    <div className="quiet-note"><Icon name="info" size={15}/><span>Pipeline activity is saved locally. “Check saved evidence” measures the age of captured sources; live monitoring and SAP C4C integration are production next steps.</span></div>
    {selected&&<Modal title="Opportunity workspace" onClose={()=>!busy&&setSelected(null)}><div className="modal-company"><CompanyMark name={selected.lead.name}/><div><strong>{selected.lead.name}</strong><span>{selected.product_name}</span></div><button className="text-button" onClick={()=>navigate(`/leads/${selected.run_id}/${selected.lead.id}`)}>Assessment<Icon name="arrow" size={14}/></button></div><form onSubmit={save}><label className="form-label" htmlFor="pipeline-stage">Pipeline stage</label><select id="pipeline-stage" value={status} onChange={e=>setStatus(e.target.value)} className="full">{columns.map(([id,title])=><option key={id} value={id} disabled={id!==selected.status&&!({qualified:['contacted','closed'],contacted:['discovery','closed'],discovery:['closed'],closed:[]}[selected.status]||[]).includes(id)}>{title}</option>)}</select><label className="form-label" htmlFor="pipeline-note">Customer update or next action <span>Required</span></label><textarea id="pipeline-note" value={note} onChange={e=>setNote(e.target.value)} rows={3} required minLength={5} placeholder="What changed? Capture the context for the next conversation."/><ErrorNotice error={error}/><div className="modal-actions"><Button kind="primary" type="submit" disabled={busy||note.trim().length<5}>{busy?'Saving...':'Save update'}</Button></div></form><div className="freshness-check"><div><strong>Source freshness</strong><small>Original capture: {when(selected.refresh?.captured_at)}</small>{selected.refresh?.checked_at&&<small>Age checked: {when(selected.refresh.checked_at)}</small>}</div><Button kind="secondary" icon="refresh" onClick={refreshEvidence} disabled={busy}>Check saved evidence</Button></div><h3 className="activity-title">Activity history</h3><div className="activity-list">{[...(selected.history||[])].reverse().map((a,i)=><div key={i}><span className="activity-dot"/><div><strong>{pretty(a.event)}</strong><p>{a.detail}</p><small>{when(a.at)}</small></div></div>)}</div></Modal>}
  </>
}
